openapi: 3.2.0
info:
  title: search-a-licious Off Test API
  description: 'The Search-a-licious API helps you quickly build applications with search capabilities.


    You can find the API documentation here.


    See also the available web-components to build your search interface.


    See the project for more information.'
  contact:
    name: The Open Food Facts team
    url: https://world.openfoodfacts.org/
    email: contact@openfoodfacts.org
  license:
    name: ' AGPL-3.0'
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: 0.1.0
tags:
- name: Off Test
paths:
  /off-test:
    get:
      summary: Html Search
      operationId: html_search_off_test_get
      parameters:
      - name: q
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Q
      - name: page
        in: query
        required: false
        schema:
          type: integer
          default: 1
          title: Page
      - name: page_size
        in: query
        required: false
        schema:
          type: integer
          default: 24
          title: Page Size
      - name: langs
        in: query
        required: false
        schema:
          type: string
          default: fr,en
          title: Langs
      - name: sort_by
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Sort By
      - name: index_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: "Index ID to use for the search, if not provided, the default index is used.\n        If there is only one index, this parameter is not needed."
          title: Index Id
        description: "Index ID to use for the search, if not provided, the default index is used.\n        If there is only one index, this parameter is not needed."
      - name: display_debug
        in: query
        required: false
        schema:
          type: boolean
          default: false
          title: Display Debug
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Off Test
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
